#!/usr/bin/env bash
## Description: Poll if Minio appears to be accessible externally.
## Usage: flysystem-minio-external-poll
#ddev-generated

URL="$DDEV_PRIMARY_URL:10101"
echo -n "Checking if minio is accessible from $URL..." 
while true ; do
  RESPONSE_CODE=$(curl -w '%{response_code}' -o /dev/null $URL 2> /dev/null)
  if [ "$RESPONSE_CODE" == "403" ] ;
    echo " hit it!"
    exit 0
  else
    echo -n "."
    sleep 1
  fi
done
