#!/usr/bin/env bash
## Description: Initializes buckets for drupal
## Usage: init-buckets
#ddev-generated

bucket=minio/flysystem

if mc ls $bucket; then
  mc rm --recursive --force $bucket
  mc rb $bucket
fi
mc mb $bucket

